### ISSUE TITLE
Windows Desktop App Authentication

### ISSUE THREAD

**Issue by lmeyers** [nuclia/support#10]
When the desktop session times out, I am unable to reauthenticate. My workaround is to close the app, reopen and authenticate. I've also had issue that long running syncs sometimes result in white out of app and need to close and reopen.  

Not sure if it common use case, but I just imported 400 resources from a single source via the Desktop app and wish to tag them all with a Label identifying the source.  There is no easy way to filter the Resource List by connector to use select all, so I must select each one individually to bulk assign the labels.  Maybe row selectors can use the Shift command to select sequential rows. Or possibly a default Label can be assigned within desktop app for the Sync.  Just a thought...

Web app activity log is not displaying resources nor queries.

**Comment by ebrehault** [comment]
Hi!
Thank you for reporting these issues.
We are currently working on improving the desktop app stability.

Regarding the labelling of resources imported from a connector, that's indeed a good ides, thank you, we have added this feature to our roadmap, we will release it shortly.

**Comment by ebrehault** [comment]
Hi!
The authentication issue should be fixed in the latest version.

**Comment by ebrehault** [comment]
The last version (2.6.19) allows to set labels in a connector.
