### ISSUE TITLE
Media State: Processing 

### ISSUE THREAD

**Issue by arky** [nuclia/support#2]
Currently there is no indication to show that the document, media file is being processed after upload. You'll only get a empty preview, when you check the page

![image](https://user-images.githubusercontent.com/808895/195828706-98b1a24a-03da-48d9-9b7c-f0532af3c3b1.png)

Testcase
------------
1. Log into cloud platform 
2. Upload a PDF document 
3. Select the PDF document. 

Expected Behavior:  Show an icon to show the processing/pending state in the preview page.

**Comment by ebrehault** [comment]
The fix has been deployed to production today.
