### ISSUE TITLE
Support for Asian languages

### ISSUE THREAD

**Issue by arky** [nuclia/support#3]
Currently there is no support any Asian languages. If you upload any document that contains non-latin characters such Khmer (km) it would not processed and rendered correctly. 

Also there is no way to pass the language code via the nuclia cloud interface. 

![image](https://user-images.githubusercontent.com/808895/195831539-70cbcac0-7a21-4bc8-8daf-63428e836b44.png)

**Comment by ebrehault** [comment]
I will close this issue as Khmer characters are now supported (among other asian languages).
