### ISSUE TITLE
Error when connecting Dropbox

### ISSUE THREAD

**Issue by Dealbergaria** [nuclia/support#5]
I followed the instructions to generate a token from my Dropbox account. I launched the Desktop App for Mac, logged in, Selected Upload from Dropbox, entered the Token, when I click "Next Steps" the next screen then gives me an error (Unexpected token E in JSON at position 0) and doesn't allow me to continue. I tried to regenerate different tokens and it still gives me the same error.

I use a MacBook Air M2, OS Ventura 13.2.1, Nuclia desktop V 1.2.4 

<img width="1277" alt="Screenshot 2023-04-04 at 10 40 27 PM" src="https://user-images.githubusercontent.com/62522822/229968338-373db080-c133-4ec6-bf81-fb6dd9c7dbe8.png">

**Comment by ebrehault** [comment]
We are currently working on a major refactoring of our desktop app that will this problem.
It is expected to be released in the coming days.

Sorry for the inconvinience.

**Comment by ebrehault** [comment]
Hi @Dealbergaria,

Our refactoring is done, the last version of the Nuclia desktop app should allow you to sync your Dropbox files properly.
