### ISSUE TITLE
Account users and KnowledgeBox users

### ISSUE THREAD

**Issue by flipmcf** [nuclia/support#9]
Not sure if this is a desired feature, but seems awkward - at least for me.   Not even sure if I should report it.

"Manage Account" has a list of users, but those users don't have access to knowledgeboxes.

You must add the user to the knowledgebox for them to have access to the KB dashboard.

---
Is there a desire to have account managers in "Account users management" that do not have read access to Knowledgeboxes?

Maybe an Account Management user can automaticaly have access to Knowledgeboxes - like it's an 'inherited' permission?

I bet there is a good reason for the two separate lists, but I've already made the mistake of adding users to the wrong list.   Managers get 404's accessing the knowledgebox and I have to add another user - the same user - twice?

**Comment by ebrehault** [comment]
It allows to have users able to manage the account (typically, manage payment and billing), while they do not need to use the service itself.
